[package]
name = "l3g4200d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitmask = "0.5.0"
i2cdev = "0.6.0"
log = "0.4.21"
thiserror = "1.0.57"
